# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'cucumber', '~> 2.4'
gem 'rest-client', '~> 2.0', '>= 2.0.2'
gem 'rspec-expectations', '~> 3.4'
gem 'pry', '~> 0.10.3'
gem 'webmock', '~> 3.4', '>= 3.4.2'
